import { useEffect, useState } from "react";
import { Edit, Plus, Trash2, UtensilsCrossed } from "lucide-react";
import { adminApi } from "@/services/api";
import { Category, MenuItem } from "@/type/type";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Label } from "@/components/ui/label";
import { Switch } from "@/components/ui/switch";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { useToast } from "@/hooks/use-toast";

const emptyItem: Omit<MenuItem,"id"> = {name:"",description:"",description_ko:null,description_ja:null,description_cn:null,description_vi:null,description_ru:null,description_kz:null,description_es:null,description_fr:null,description_it:null,price:0,vat:0,category_id:null,image_url:null,active:true,display_order:0};
const emptyCategory: Omit<Category,"id"> = {name:"",display_name:"",display_order:0,is_active:true};

export default function AdminMenu(){
 const [items,setItems]=useState<MenuItem[]>([]),[categories,setCategories]=useState<Category[]>([]);
 const [item,setItem]=useState<(Omit<MenuItem,"id">&{id?:string})|null>(null),[category,setCategory]=useState<(Omit<Category,"id">&{id?:string})|null>(null);
 const {toast}=useToast();
 const load=async()=>{try{const [i,c]=await Promise.all([adminApi.menuItems(),adminApi.menuCategories()]);setItems(i);setCategories(c);}catch(e){toast({title:"Cannot load menu",description:e instanceof Error?e.message:"Please try again",variant:"destructive"});}};
 useEffect(()=>{void load();},[]);
 const saveItem=async()=>{if(!item?.name||!item.description)return;try{item.id?await adminApi.updateMenuItem(item as MenuItem):await adminApi.createMenuItem(item);setItem(null);await load();toast({title:"Menu item saved"});}catch(e){toast({title:"Cannot save item",description:e instanceof Error?e.message:"Please try again",variant:"destructive"});}};
 const saveCategory=async()=>{if(!category?.display_name)return;const value={...category,name:category.name||category.display_name};try{category.id?await adminApi.updateMenuCategory(value as Category):await adminApi.createMenuCategory(value);setCategory(null);await load();toast({title:"Category saved"});}catch(e){toast({title:"Cannot save category",description:e instanceof Error?e.message:"Please try again",variant:"destructive"});}};
 return <div className="space-y-5"><div><h2 className="text-2xl font-semibold">Menu</h2><p className="text-sm text-muted-foreground">The customer menu and admin panel now use the same backend database.</p></div>
 <Tabs defaultValue="items"><TabsList><TabsTrigger value="items">Menu items</TabsTrigger><TabsTrigger value="categories">Categories</TabsTrigger></TabsList>
 <TabsContent value="items" className="space-y-4"><div className="flex justify-end"><Button onClick={()=>setItem({...emptyItem})}><Plus className="mr-2 h-4 w-4"/>Add item</Button></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{items.map(v=><div key={v.id} className={`overflow-hidden rounded-xl border bg-white ${v.active===false?"opacity-60":""}`}>{v.image_url?<img src={v.image_url} alt={v.name} className="h-40 w-full object-cover"/>:<div className="flex h-40 items-center justify-center bg-muted"><UtensilsCrossed className="h-10 w-10 text-muted-foreground"/></div>}<div className="space-y-2 p-4"><div className="flex justify-between gap-2"><h3 className="font-semibold">{v.name}</h3><span className="whitespace-nowrap font-semibold text-primary">{v.price.toLocaleString("vi-VN")} ₫</span></div><p className="line-clamp-2 text-sm text-muted-foreground">{v.description}</p><div className="flex gap-2"><Button variant="outline" className="flex-1" onClick={()=>setItem({...v})}><Edit className="mr-1 h-4 w-4"/>Edit</Button><Button variant="destructive" size="icon" onClick={async()=>{if(confirm(`Delete ${v.name}?`)){await adminApi.deleteMenuItem(v.id);await load();}}}><Trash2 className="h-4 w-4"/></Button></div></div></div>)}</div></TabsContent>
 <TabsContent value="categories" className="space-y-4"><div className="flex justify-end"><Button onClick={()=>setCategory({...emptyCategory})}><Plus className="mr-2 h-4 w-4"/>Add category</Button></div>{categories.map(v=><div key={v.id} className="flex items-center justify-between rounded-xl border bg-white p-4"><div><p className="font-medium">{v.display_name}</p><p className="text-sm text-muted-foreground">Order {v.display_order} · {v.is_active?"Active":"Hidden"}</p></div><div className="flex gap-2"><Button variant="outline" size="icon" onClick={()=>setCategory({...v})}><Edit className="h-4 w-4"/></Button><Button variant="destructive" size="icon" onClick={async()=>{if(confirm(`Delete ${v.display_name}?`)){try{await adminApi.deleteMenuCategory(v.id);await load();}catch(e){toast({title:"Cannot delete category",description:e instanceof Error?e.message:"Please try again",variant:"destructive"});}}}}><Trash2 className="h-4 w-4"/></Button></div></div>)}</TabsContent></Tabs>
 <Dialog open={!!item} onOpenChange={open=>!open&&setItem(null)}><DialogContent className="max-h-[90vh] overflow-y-auto"><DialogHeader><DialogTitle>{item?.id?"Edit":"Add"} menu item</DialogTitle></DialogHeader>{item&&<div className="grid gap-4"><Label>Name<Input value={item.name} onChange={e=>setItem({...item,name:e.target.value})}/></Label><Label>English description<Textarea value={item.description} onChange={e=>setItem({...item,description:e.target.value})}/></Label><div className="grid grid-cols-2 gap-3"><Label>Price<Input type="number" value={item.price} onChange={e=>setItem({...item,price:Number(e.target.value)})}/></Label><Label>VAT %<Input type="number" value={item.vat} onChange={e=>setItem({...item,vat:Number(e.target.value)})}/></Label></div><Label>Category<Select value={item.category_id||"none"} onValueChange={v=>setItem({...item,category_id:v==="none"?null:v})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="none">Uncategorized</SelectItem>{categories.map(c=><SelectItem key={c.id} value={c.id}>{c.display_name}</SelectItem>)}</SelectContent></Select></Label><Label>Image URL<Input value={item.image_url||""} onChange={e=>setItem({...item,image_url:e.target.value||null})}/></Label><Label>Vietnamese description<Textarea value={item.description_vi||""} onChange={e=>setItem({...item,description_vi:e.target.value||null})}/></Label><div className="flex items-center gap-2"><Switch checked={item.active??true} onCheckedChange={v=>setItem({...item,active:v})}/><Label>Visible to customers</Label></div><Button onClick={saveItem}>Save item</Button></div>}</DialogContent></Dialog>
 <Dialog open={!!category} onOpenChange={open=>!open&&setCategory(null)}><DialogContent><DialogHeader><DialogTitle>{category?.id?"Edit":"Add"} category</DialogTitle></DialogHeader>{category&&<div className="grid gap-4"><Label>Display name<Input value={category.display_name} onChange={e=>setCategory({...category,display_name:e.target.value,name:e.target.value})}/></Label><Label>Display order<Input type="number" value={category.display_order} onChange={e=>setCategory({...category,display_order:Number(e.target.value)})}/></Label><div className="flex items-center gap-2"><Switch checked={category.is_active} onCheckedChange={v=>setCategory({...category,is_active:v})}/><Label>Visible</Label></div><Button onClick={saveCategory}>Save category</Button></div>}</DialogContent></Dialog></div>;
}
